version: '3.3'

services:
  database:
    image: postgres:13
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: comments
    ports:
      - "5432:5432"

  web:
    image: thejas2843/commentsapp:v1
    ports:
      - "5000:5000"
    depends_on:
      - database
    environment:
      - SQLALCHEMY_DATABASE_URI=postgresql://user:password@database:5432/comments